; PictureAndVideos Setup Script
; Generated by Inno Setup

#define MyAppName "PictureAndVideos"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Picture Sharing"
#define MyAppURL "http://localhost:5001/pic"
#define MyAppExeName "PictureAndVideos.exe"

[Setup]
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=installer_output
OutputBaseFilename=PictureAndVideos-Setup-v{#MyAppVersion}
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
AppCopyright=Copyright (C) 2026
WizardImageStretch=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked
Name: "launchonfinish"; Description: "Launch program when installation completes"; GroupDescription: "After installation:"; Flags: unchecked

[Files]
Source: "dist\PictureAndVideos\PictureAndVideos.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\PictureAndVideos\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{group}\卸载 {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "启动 {#MyAppName}"; WorkingDir: "{app}"; Flags: nowait postinstall skipifsilent; Tasks: launchonfinish

[UninstallDelete]
Type: filesandordirs; Name: "{app}\user"
Type: filesandordirs; Name: "{app}\picture"
Type: filesandordirs; Name: "{app}\comments"
Type: filesandordirs; Name: "{app}\BanRecord"
Type: filesandordirs; Name: "{app}\groupchat"
Type: filesandordirs; Name: "{app}\videos"
Type: filesandordirs; Name: "{app}\data"
Type: filesandordirs; Name: "{app}\static"
Type: filesandordirs; Name: "{app}\logs"
